language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode8.3
r_packages:
- covr
- drat
after_failure:
  email: 
    recipients:
     - thosjleeper@gmail.com
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: StCqL9v/F4eC570QB9Ih2im+cJJkGaCTOk5c3DBY3yK+MHVppGWHPntEEIyTtYf314I9zIfEw7CcQFLRMaESzZu1Hiv06oAQyY/9qw9UrWaxwQmJy0ESSle6gxhvyNUZUY3NkWjnoGAVNb1LUCJ9FHp3kYga0Zh4eW1/I2Il5Uwa6p+rr4ukjORwyDArIymb9vs940oyfcd9QbMtxCsfuAgdsqf02gRRQ3tts+NA49kGzqdb3kgPGQC/HkTO+Nkvgz8WFgwZBIJRq3rD9NVAD+m7s/CMMlsrsD1RXkUy8ileGhjk9UQwW2p2AjgrUwKwvhtgjUuUxcZrqOgUywMGCXGxIknHxPfc1rNJDsmZ5JcUvXXLC7RPdOrzf6gBqJpeCBDB9thBXgGwINono5oivrfGLLc5KWXQkhaYByrQkGv1VnaOqNgV6FAoA6DE4Cu/DktnZpwMGV3OaI+Dm54JIn038KxJD852msylwfQ3qyJZAu7gKcFxkdFXTCOx4OAivFggnvFIvPQGPNOBnjliZS/x8hyWhH5UzoEuagYTpEzEAlhkv48a8oFsLdxYXO6wcQcVMz6TpOXQqlNx9/mPMzvWUqnV9SvQ14BRHUP+y2HSuEPOUX4k2y4+3A08hI5xhHIq8foFG5lXbFHJPayjH9ly093zyxr7t6qPcElxPBA=
